# (bool) Whether to enable radiation at the start of the round
enable_radiation_on_round_start: true
# (float) How many seconds to wait after warhead detonation before starting radiation
radiation_delay: 300
# (string) The reason that gets used on Damage and Kill methods
death_reason: Died to alpha warhead radiation.
# (float) How many seconds to wait between dealing damage
tick_interval: 2
# (float) Damage dealt to players specified as a constant
tick_damage_absolute: 10
# (float) Damage dealt to players specified as a percentage
tick_damage_relative: 5
# (bool) Whether to show a broadcast when radiation starts
broadcast_enable: true
# (string) What text should be in the broadcast
broadcast_text: Warhead radiation has reached the surface!
# (ushort) How many seconds the broadcast should be displayed for
broadcast_duration: 10
# (bool) Whether to show a hint when radiation starts and to players whose role changes
hint_enable: false
# (string) What text should be in the hint
hint_text: Radiation Poisoning
# (ushort) How many seconds the hint should be displayed for
hint_duration: 10
# (List<RoleTypeId>) What roles should be dealt constant damage to
takes_absolute_damage:
- ChaosConscript
- ChaosMarauder
- ChaosRepressor
- ChaosRifleman
- ClassD
- FacilityGuard
- NtfCaptain
- NtfPrivate
- NtfSergeant
- NtfSpecialist
- Scientist
- Tutorial
# (List<RoleTypeId>) What roles should be dealt percentage damage to
takes_relative_damage:
- Scp049
- Scp0492
- Scp096
- Scp106
- Scp173
- Scp939
